services:
  - type: web
    name: rentwithmsbackend
    runtime: node
    buildCommand: cd backend && npm install && npx prisma generate && cd ..
    startCommand: cd backend && npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
